language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - npm install -g
  - npm install -g gulp
  - npm install -g karma
  - npm install angularjs
  - npm install angular-mocks
  - npm install
  - gulp test